name: Prepare Build
description: Setup Node, install dependencies, and build the project.

inputs:
  node-version:
    description: Node.js version for setup-node.
    required: false
    default: lts/*

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install packages
      shell: bash
      run: npm install

    - name: Build
      shell: bash
      run: npm run build
