name: Release

on:
  push:
    paths:
      - package.json

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare build
        uses: ./.github/actions/prepare-build

      - name: Tar
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./bin
          outPath: transpiled.tar.gz

      - name: Getting release version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Package release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            transpiled.tar.gz
          tag_name: ${{ steps.package-version.outputs.current-version }}
          make_latest: true
