name: Release

on:
  push:
    paths:
      - package.json

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Prepare build
        uses: ./.github/actions/prepare-build
        env:
          READ_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tar
        run: tar -czf transpiled.tar.gz ./bin

      - name: Getting release version
        id: package-version
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          echo "current-version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Package release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.package-version.outputs.current-version }}
        run: |
          gh release create "${VERSION}" transpiled.tar.gz \
            --target "${GITHUB_SHA}" \
            --title "${VERSION}" \
            --notes "" \
            --latest

  build-container:
    needs: build
    uses: ./.github/workflows/build-container.yml
    with:
      new_release_created: true
    secrets: inherit
